### ISSUE TITLE
Добавить проверку: был ли плагин уже инициализирован?

### ISSUE THREAD

**Issue by asg-3d** [peremenov/jquery-factory#2]
Можно ли добавить в фабрику проверку, был этот плагин уже инициализирован или нет?
Сейчас приходится писать так:

``` javascript
// --- Init plugin ---
Plugin.prototype.init = function() {
    var self = this;

    if (self.$element.data('plugin') == 'initialised') {
        return;
    } else {
        self.$element.data('plugin', 'initialised');
    }
};
```

**Comment by peremenov** [comment]
Если плагин инициализирован на элементе, вместо конструктора вызовется метод `update`

Если же нужна проверка, действительно ли это тот плагин, что нужен, в последнем обновлении было добавлено свойство с конструктором плагина:

``` javascript
self.$element.data('plugin') instanceof $.fn.plugin.__constr__
```

**Comment by asg-3d** [comment]
> Если плагин инициализирован на элементе, вместо конструктора вызовется метод `update`

Тогда другое дело :+1:

**Comment by asg-3d** [comment]
Ошибочно открыл заново. Можешь удалить этот коммент?)

**Comment by peremenov** [comment]
Обновил readme
